name: hs-test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

        with:
          submodules: true
          persist-credentials: false
          token: ${{ secrets.PAT }}

      - run: npm install
      - run: npm run build
      - run: Cypress run
