name: hs-test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      
      - name: Build
        uses: actions/checkout@v2    
        with:
            persist-credentials: false
            token: ${{ secrets.PAT }}

      - run: npm install
      - run: npm run build
        
      
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
            persist-credentials: false
            token: ${{ secrets.PAT }}
            browser: chrome
        

      


